models.py
from flask_login import UserMixin

class User(UserMixin):
    def __init__(self, user_id):
        self.id = user_id

app.py
from flask import Flask
from flask_login import LoginManager
from flask_session import Session

app = Flask(__name__)
app.secret_key = '123456'

app.config['SESSION_TYPE'] = 'filesystem'
Session(app)

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'routes.login'

UPLOAD_FOLDER = 'uploads'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

DOWNLOAD_FOLDER = 'downloads'
app.config['DOWNLOAD_FOLDER'] = DOWNLOAD_FOLDER

main.py
import os
from flask import Flask
from flask_login import LoginManager
from mysql.connector import connect, Error
from db_config import create_connection, close_connection
from models import User
from app import app, login_manager

if not os.path.exists(app.config['UPLOAD_FOLDER']):
    os.makedirs(app.config['UPLOAD_FOLDER'])

if not os.path.exists(app.config['DOWNLOAD_FOLDER']):
    os.makedirs(app.config['DOWNLOAD_FOLDER'])

@login_manager.user_loader
def load_user(user_id):
    connection = create_connection()
    try:
        cursor = connection.cursor(dictionary=True)
        cursor.execute("SELECT user_id FROM user WHERE user_id = %s", (user_id,))
        user = cursor.fetchone()
    except Error as e:
        print(f"Erro ao acessar o banco de dados: {e}")
        user = None
    finally:
        cursor.close()
        connection.close()
        
    if user:
        return User(user['user_id'])
    return None

from routes import routes
app.register_blueprint(routes)

if __name__ == '__main__':
    app.run(debug=True)

routes.py
from flask import Blueprint, current_app, jsonify, render_template, redirect, send_file, url_for, request, flash, session
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import check_password_hash, generate_password_hash
import os
from db_config import create_connection
from app import app
from models import User
import requests

routes = Blueprint('routes', __name__)

@app.route('/')
def index():
    return redirect(url_for('routes.home'))

@routes.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        connection = create_connection()
        if not connection:
            flash("Erro ao conectar ao banco de dados")
            return render_template('login.html')

        cursor = connection.cursor()
        try:
            cursor.execute("""SELECT user_id, email, password FROM user WHERE email = %s""", (email,))
            user = cursor.fetchone()

            if user and check_password_hash(user[2], password):
                login_user(User(user[0]))
                return redirect(url_for('routes.home'))
            else:
                flash('Email ou senha incorretos')
        except Exception as e:
            flash(f"Erro ao realizar login: {e}")
        finally:
            cursor.close()
            connection.close()

    return render_template('login.html')

@routes.route('/home', methods=['GET', 'POST'])
@login_required
def home():

    current_user_id = int(session.get('_user_id'))
    if not current_user_id:
        return jsonify(error="Usuário não autenticado."), 403
    connection = create_connection()
    cursor = connection.cursor(dictionary=True)
    try:
        cursor.execute("SELECT book_id, title, author, whatsapp, book_type, cover_url, description, user_id FROM book")
        books = cursor.fetchall()
        for book in books:
            book['current_user'] = current_user_id
    except Exception as e:
        print(f"Erro ao carregar os livros: {e}")
        flash(f"Erro ao carregar os livros: {e}")
        books = []
    finally:
        cursor.close()
        connection.close()
    return render_template('home.html', books=books)


@routes.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('routes.login'))


@routes.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        nome = request.form['nome']
        telefone = request.form['telefone']
        email = request.form['email']
        password = request.form['password']

        connection = create_connection()
        if not connection:
            flash("Erro ao conectar ao banco de dados")
            return render_template('register.html')

        cursor = connection.cursor()
        try:
            cursor.execute("SELECT email FROM user WHERE email = %s", (email,))
            existing_user = cursor.fetchone()
            if existing_user:
                flash("Email já cadastrado. Tente outro.")
                return render_template('register.html')

            hashed_password = generate_password_hash(password)

            cursor.execute("""INSERT INTO user (name, phone, email, password) 
                              VALUES (%s, %s, %s, %s)""",
                           (nome, telefone, email, hashed_password))
            connection.commit()
            flash("Registro realizado com sucesso! Você pode fazer login agora.")
            return redirect(url_for('routes.login'))
        except Exception as e:
            flash(f"Erro ao registrar: {e}")
        finally:
            cursor.close()
            connection.close()

    return render_template('register.html')




@routes.route('/add_book', methods=['POST'])
@login_required
def add_book():

    current_user_id = int(session.get('_user_id'))
    if not current_user_id:
        return jsonify(error="Usuário não autenticado."), 403
    
    title = request.form.get('bookTitle')
    author = request.form.get('bookAuthor')
    whatsapp = request.form.get('whatsapp')
    book_type = request.form.get('bookType')
    cover_url = request.form.get('coverUrl')
    description = request.form.get('description')


    if not title or not author or not whatsapp or not book_type:
        return jsonify({"error": "Todos os campos são obrigatórios"}), 400
    
    connection = create_connection()
    cursor = connection.cursor()
    try:
        cursor.execute("""
            INSERT INTO book (title, author, whatsapp, book_type, cover_url, description, user_id)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """, (title, author, whatsapp, book_type, cover_url, description, current_user_id))
        connection.commit()
        return jsonify({"success": "Livro adicionado com sucesso!"}), 200
    except Exception as e:
        connection.rollback()
        print("Erro ao adicionar ao banco:", e)
        return jsonify({"error": str(e)}), 500
    finally:
        cursor.close()
        connection.close()



@app.route('/delete_book/<int:book_id>', methods=['DELETE'])
def delete_book(book_id):

    current_user_id = int(session.get('_user_id'))
    if not current_user_id:
        return jsonify(error="Usuário não autenticado."), 403

    conn = create_connection()
    cursor = conn.cursor(dictionary=True) 
    try:
        cursor.execute("SELECT * FROM book WHERE book_id = %s", (book_id,))
        book = cursor.fetchone()
        print(book)

        if book and book['user_id'] == current_user_id:
            cursor.execute("DELETE FROM book WHERE book_id = %s", (book_id,))
            conn.commit()
            return jsonify({'success': 'Livro excluído com sucesso!'}), 200
        else:
            return jsonify({'error': 'Ação não permitida!'}), 403
    except Exception as e:
        conn.rollback()
        print("Erro ao excluir do banco:", e)
        return jsonify({"error": str(e)}), 500
    finally:
        cursor.close()
        conn.close()

templates/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Página Inicial - Ubá Leitor</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">  <!-- Adicionando o CSS -->
</head>
<body>
    <div class="container mt-5">
        <h1>Livros Disponíveis</h1>
        <button class="btn btn-primary" id="addBookBtn">Adicionar Novo Anúncio</button>
        <div id="books-list" class="mt-4 row">
            {% for book in books %}
            <div class="col-md-3 book-item" onclick="showBookDetails({
                title: '{{ book.title }}',
                author: '{{ book.author }}',
                description: '{{ book.description }}',
                cover_url: '{{ book.cover_url }}',
                whatsapp: '{{ book.whatsapp }}'
            })">
                <img src="{{ book.cover_url }}" alt="Capa do Livro" class="book-cover">
                <div>
                    <h5>{{ book.title }}</h5>
                    <p>Autor: {{ book.author }}</p>
                    <span class="badge badge-{{ 'success' if book.book_type == 'doacao' else 'primary' }}">
                        {{ 'Doação' if book.book_type == 'doacao' else 'Troca' }}
                    </span>
                    {% if book.user_id == current_user.id %}
                    <button class="btn btn-danger btn-sm delete-btn" onclick="confirmDelete('{{ book.book_id }}', event)">
                        🗑️
                    </button>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="modal fade" id="bookDetailsModal" tabindex="-1" role="dialog" aria-labelledby="bookDetailsLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document"> <!-- Modal grande -->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="bookDetailsLabel">Detalhes do Livro</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body d-flex">
                    <div class="mr-4">
                        <img id="modal-book-cover" src="" alt="Capa do Livro" class="img-fluid" style="max-width: 150px; max-height: 225px; object-fit: cover;">
                    </div>
                    <div>
                        <h5 id="modal-book-title" class="font-weight-bold"></h5>
                        <p id="modal-book-author" class="text-muted"></p>
                        <p id="modal-book-description" class="text-justify"></p>
                        <a id="modal-whatsapp-link" href="#" target="_blank" class="btn btn-success">Contactar pelo WhatsApp</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

    <div class="modal fade" id="addBookModal" tabindex="-1" role="dialog" aria-labelledby="addBookLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document"> <!-- Modal grande -->
            <div class="modal-content">
                <div class="modal-header bg-white text-black">
                    <h5 class="modal-title" id="addBookLabel">Adicionar Novo Anúncio</h5>
                    <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="addBookForm">
                        <div class="form-group">
                            <label for="bookTitle">Título do Livro</label>
                            <input type="text" class="form-control rounded-pill" id="bookTitle" name="bookTitle" required autocomplete="off">
                            <div id="autocomplete-list" class="autocomplete-list"></div>
                        </div>
                        <div class="form-group">
                            <label for="bookAuthor">Autor</label>
                            <input type="text" class="form-control rounded-pill" id="bookAuthor" name="bookAuthor" required>
                        </div>
                        <div class="form-group">
                            <label for="whatsapp">Número do WhatsApp</label>
                            <input type="text" class="form-control rounded-pill" id="whatsapp" name="whatsapp" placeholder="Telefone com DDD (Apenas números)" required>
                        </div>
                        <div class="form-group">
                            <label for="bookType">Tipo de Anúncio</label>
                            <select class="form-control rounded-pill" id="bookType" name="bookType" required>
                                <option value="doacao">Doação</option>
                                <option value="troca">Apenas Troca</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="hidden" class="form-control" id="coverUrl" name="coverUrl">
                        </div>
                        <div class="form-group">
                            <label for="description">Descrição</label>
                            <textarea class="form-control rounded" id="description" name="description" rows="3" placeholder="Descrição do livro"></textarea>
                        </div>
                        <div class="form-group text-center">
                            <label>Pré-visualização da Capa</label>
                            <div id="coverPreview">
                                <img id="previewCover" src="https://via.placeholder.com/150x225" alt="Pré-visualização da Capa" class="img-fluid rounded" style="max-width: 150px; max-height: 225px; object-fit: cover; display: none; border: 2px solid #007bff; padding: 5px;">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block rounded-pill">Confirmar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>  <!-- Adicionando o JavaScript -->
</body>
</html>

templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-image: url("{{ url_for('static', filename='images/background.jpg') }}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
        .form-container {
            background-color: #e0df8f;
            border-radius: 15px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            padding: 30px;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="text-center mt-5">
                    <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo" class="img-fluid" style="max-width: 40%;">
                </div>
                <div class="form-container">
                    <h1 class="text-center">Login</h1>
                    <form method="post" class="mt-4">
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" id="email" name="email" class="form-control" placeholder="Digite seu email" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Senha</label>
                            <input type="password" id="password" name="password" class="form-control" placeholder="Digite sua senha" required>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block mt-3">Entrar</button>
                    </form>
                    
                    {% with messages = get_flashed_messages() %}
                      {% if messages %}
                        <div class="alert alert-danger mt-3">
                          <ul class="mb-0">
                            {% for message in messages %}
                              <li>{{ message }}</li>
                            {% endfor %}
                          </ul>
                        </div>
                      {% endif %}
                    {% endwith %}
                    
                    <div class="mt-3 text-center">
                        <a href="{{ url_for('routes.register') }}" class="btn btn-link">Registrar-se</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/register.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Registrar-se</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h1 class="mt-5">Registrar-se</h1>
                <form method="post" class="mt-4">
                    <div class="form-group">
                        <label for="nome">Nome</label>
                        <input type="text" id="nome" name="nome" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="telefone">Telefone</label>
                        <input type="text" id="telefone" name="telefone" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" id="email" name="email" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="password">Senha</label>
                        <input type="password" id="password" name="password" class="form-control" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Registrar</button>
                </form>
                {% with messages = get_flashed_messages() %}
                  {% if messages %}
                    <div class="alert alert-danger mt-3">
                      <ul class="mb-0">
                        {% for message in messages %}
                          <li>{{ message }}</li>
                        {% endfor %}
                      </ul>
                    </div>
                  {% endif %}
                {% endwith %}
                <div class="mt-3 text-center">
                    <a href="{{ url_for('routes.login') }}" class="btn btn-link">Voltar para Login</a>
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>